spring:
  datasource:
    url: jdbc:postgresql://catalog-db:5432/catalogdb_dev
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

logging:
  level:
    root: WARN

app:
  banner: "CATALOG running with PROD profile"
