server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://catalog-db:5432/catalogdb_prod
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: warn
