server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/mia
  datasource:
    url: jdbc:postgresql://order-db:5432/orderdb_dev
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    prefer-ip-address: true

catalog:
  base-url: http://catalog-service:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,circuitbreakers,ratelimiters,threaddump

management.health.circuitbreakers.enabled: true

management.endpoint:
  circuitbreakers.enabled: true
  ratelimiters.enabled: true

resilience4j:
  circuitbreaker:
    instances:
      catalogService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6
        minimumNumberOfCalls: 4
        failureRateThreshold: 40
        slowCallDurationThreshold: 1s
        slowCallRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.HttpServerErrorException

  retry:
    instances:
      catalogService:
        maxAttempts: 1

  ratelimiter:
    instances:
      catalogService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0

  bulkhead:
    instances:
      catalogService:
        type: SEMAPHORE
        maxConcurrentCalls: 10
        maxWaitDuration: 0

  timelimiter:
    instances:
      catalogService:
        timeoutDuration: 1s

  resilience:
    simulate-random-latency: true