server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://order-db:5432/orderdb_prod
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: warn
