server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo  # mounts through docker-compose
management:
  endpoints:
    web:
      exposure:
        include: health,info